# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

stages:
  - stage: buildstage
    jobs:
      - job: buildjob
        pool:
         vmImage: 'ubuntu-latest'
        steps:

        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
           terraformVersion: '1.6.6'

        - task: TerraformTask@5
          displayName: TF Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'Azure-Service-connection'
            backendAzureRmResourceGroupName: 'terrafor-resource-group'
            backendAzureRmStorageAccountName: 'terraformstorage2026'
            backendAzureRmContainerName: 'terraform-tfstat'
            backendAzureRmKey: 'prod.terraform.tfstate'

        # - task: TerraformTask@5
        #   displayName: tfInit
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'init'
        #    #commandOptions: '-out $(Build.SourcesDirectory)/tfplanfile'
        #     backendServiceArm: 'Azure subscription 1(1)(7b4fa607-b447-4f15-99df-721b7b10c661)'
        #     backendAzureRmResourceGroupName: 'terraform-cloud-shell-RG'
        #     backendAzureRmStorageAccountName: 'terraformcloud2026'
        #     backendAzureRmContainerName: 'terraform-tfstat1'
        #     backendAzureRmKey: 'prod.terraform.tfstate'
        - task: TerraformTask@5
          displayName: TF validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'

        - task: TerraformTask@5
          displayName: tf plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Azure-Service-connection'
            environmentAzureRmUseIdTokenGeneration: true

        - task: ArchiveFiles@2
          displayName: ArchiveFiles
          inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: PublishBuildArtifacts
          inputs:
             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             ArtifactName: '$(Build.BuildId)-build'
             publishLocation: 'Container'